package ui

import (
	"bytes"
	_ "embed"
	"fmt"
	"html"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// AssetsDir is the legend's home under the world dir.
const AssetsDir = "ui-assets"

// Write regenerates the legend under <root>/<worldDir>/ui-assets: manifest.json, legend.md and
// catalogue.html. It returns the files it changed (none when the legend was already fresh).
func Write(root, worldDir string, m *Manifest) ([]string, error) {
	dir := filepath.Join(root, worldDir, AssetsDir)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	cat, err := Catalogue(root, worldDir, m)
	if err != nil {
		return nil, err
	}
	var changed []string
	for name, body := range map[string][]byte{"manifest.json": m.JSON(), "legend.md": Legend(m), "catalogue.html": cat} {
		p := filepath.Join(dir, name)
		if old, err := os.ReadFile(p); err == nil && bytes.Equal(old, body) {
			continue
		}
		if err := os.WriteFile(p, body, 0o644); err != nil {
			return changed, err
		}
		changed = append(changed, rel(root, p))
	}
	return changed, nil
}

// Stale says which legend files differ from what the ui dir now says.
func Stale(root, worldDir string, m *Manifest) []string {
	dir := filepath.Join(root, worldDir, AssetsDir)
	var out []string
	cat, _ := Catalogue(root, worldDir, m)
	for name, body := range map[string][]byte{"manifest.json": m.JSON(), "legend.md": Legend(m), "catalogue.html": cat} {
		if old, err := os.ReadFile(filepath.Join(dir, name)); err != nil || !bytes.Equal(old, body) {
			out = append(out, filepath.ToSlash(filepath.Join(worldDir, AssetsDir, name)))
		}
	}
	return out
}

// Legend is the manifest as a page an agent reads before touching the ui: every component, the
// classes it owns, its variants and the tokens it consumes; then the global classes and tokens.
func Legend(m *Manifest) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "# UI legend — %s\n\n", m.Dir)
	b.WriteString("Generated by `ui scan` from the ui dir; never edit it — change the component and rescan.\n")
	b.WriteString("A global change is a token change: edit the meaning tier in tokens.css, never a component.\n\n")
	b.WriteString("## Components\n\n| component | owns classes | variants | reads tokens | own tokens | inputs (style/JS) | what it is |\n|---|---|---|---|---|---|---|\n")
	for _, c := range m.Components {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s | %s |\n", c.Name, code(c.Classes, "."), code(c.Variants, ""), code(c.Consumes, ""), code(c.Own, ""), code(c.Inputs, ""), strings.ReplaceAll(c.Summary, "|", "\\|"))
	}
	if len(m.Components) == 0 {
		b.WriteString("| — | | | | | | no components yet |\n")
	}
	b.WriteString("\n## System files\n\n")
	for _, g := range m.Globals {
		fmt.Fprintf(&b, "- `%s`", g.File)
		if len(g.Classes) > 0 {
			fmt.Fprintf(&b, " — classes %s", code(g.Classes, "."))
		}
		if len(g.Tokens) > 0 {
			fmt.Fprintf(&b, " — %d tokens", len(g.Tokens))
		}
		b.WriteString("\n")
	}
	b.WriteString("\n## Tokens\n\n")
	groups := map[string][]string{}
	var order []string
	for _, t := range m.Tokens {
		k := tokenGroup(t)
		if _, ok := groups[k]; !ok {
			order = append(order, k)
		}
		groups[k] = append(groups[k], t)
	}
	for _, k := range order {
		fmt.Fprintf(&b, "- **%s**: %s\n", k, code(groups[k], ""))
	}
	return []byte(b.String())
}

// tokenGroup is a token's family: its name up to the first dash-separated part (--space-m → space).
func tokenGroup(t string) string {
	name := strings.TrimPrefix(t, "--")
	if i := strings.Index(name, "-"); i > 0 {
		return name[:i]
	}
	return name
}

func code(in []string, prefix string) string {
	if len(in) == 0 {
		return "—"
	}
	parts := make([]string, len(in))
	for i, s := range in {
		parts[i] = "`" + prefix + s + "`"
	}
	return strings.Join(parts, " ")
}

// Catalogue is one page showing every component live on the app's own css: the retheme test
// surface. The theme, palette and density switch from the URL hash (#theme=dark&palette=ocean)
// or the controls; each stage reports horizontal overflow on <html data-overflow>.
func Catalogue(root, worldDir string, m *Manifest) ([]byte, error) {
	from := filepath.Join(root, worldDir, AssetsDir)
	var links, stages, palettes strings.Builder
	for _, f := range cssFiles(root, m) {
		r, err := filepath.Rel(from, filepath.Join(root, f))
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&links, "<link rel=\"stylesheet\" href=\"%s\">\n", html.EscapeString(filepath.ToSlash(r)))
		if filepath.Base(f) == "palettes.css" {
			src, _ := os.ReadFile(filepath.Join(root, f))
			for _, p := range reVariantPalette.FindAllStringSubmatch(string(src), -1) {
				fmt.Fprintf(&palettes, "<option>%s</option>", html.EscapeString(p[1]))
			}
		}
	}
	for _, c := range m.Components {
		body := "<p class=\"cat-empty\">no " + html.EscapeString(c.Name) + ".html — add a sample of the component</p>"
		if c.HTML != "" {
			if src, err := os.ReadFile(filepath.Join(root, c.HTML)); err == nil {
				body = string(src)
			}
		}
		fmt.Fprintf(&stages, `<section class="cat-item" id="c-%[1]s">
<header class="cat-head"><h2>%[1]s</h2><p>%[2]s</p>
<dl><dt>classes</dt><dd>%[3]s</dd><dt>variants</dt><dd>%[4]s</dd><dt>reads</dt><dd>%[5]s</dd><dt>own</dt><dd>%[7]s</dd><dt>inputs</dt><dd>%[8]s</dd></dl></header>
<div class="cat-stage" data-component="%[1]s">
%[6]s
</div>
</section>
`, html.EscapeString(c.Name), html.EscapeString(c.Summary), chips(dot(c.Classes)), chips(c.Variants), chips(c.Consumes), body, chips(c.Own), chips(c.Inputs))
	}
	if len(m.Components) == 0 {
		stages.WriteString(`<p class="cat-empty">No components yet: add ` + html.EscapeString(m.Dir) + `/components/&lt;name&gt;/&lt;name&gt;.{html,css}, then scan.</p>`)
	}
	page := strings.NewReplacer("{{DIR}}", html.EscapeString(m.Dir), "{{LINKS}}", links.String(), "{{STAGES}}", stages.String(), "{{PALETTES}}", palettes.String(),
		"{{COUNT}}", fmt.Sprint(len(m.Components))).Replace(catalogueTemplate)
	return []byte(page), nil
}

// chips are names that never break inside: one <code> each.
func chips(in []string) string {
	if len(in) == 0 {
		return "—"
	}
	parts := make([]string, len(in))
	for i, s := range in {
		parts[i] = "<code>" + html.EscapeString(s) + "</code>"
	}
	return strings.Join(parts, " ")
}

func dot(in []string) []string {
	out := make([]string, len(in))
	for i, s := range in {
		out[i] = "." + s
	}
	return out
}

var reVariantPalette = regexp.MustCompile(`\[data-palette\s*=\s*"?([\w-]+)"?\]`)

//go:embed assets/catalogue.html
var catalogueTemplate string
